name: Build & Release

on:
  push:
    tags:
      - "v*.*"
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: Install Node.js dependencies
        run: npm ci
      - name: Build win32 and win64 binaries
        run: npm run build-win --if-present
      - name: "Zip : win32"
        uses: papeloto/action-zip@v1
        with:
          files: dist/smartcontract-caller/win32
          dest: smartcontract-caller-win32.zip
      - name: "Upload artifact : win32"
        uses: actions/upload-artifact@v1
        with:
          name: smartcontract-caller-win32
          path: ${{ github.workspace }}/smartcontract-caller-win32.zip
      - name: "Zip : win64"
        uses: papeloto/action-zip@v1
        with:
          files: dist/smartcontract-caller/win64
          dest: smartcontract-caller-win64.zip
      - name: "Upload artifact : win64"
        uses: actions/upload-artifact@v1
        with:
          name: smartcontract-caller-win64
          path: ${{ github.workspace }}/smartcontract-caller-win64.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.workspace }}/smartcontract-caller-win32.zip
            ${{ github.workspace }}/smartcontract-caller-win64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
