# This is a basic workflow to help you get started with Actions

name: Smartcontract Caller Build & Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - "v*.*"
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 15.x
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: Install dependencies
        run: npm ci
      - name: Build win32 and win64 binaries
        run: npm run build-win --if-present
      - name: zip win32 folder
        uses: papeloto/action-zip@v1
        with:
          files: dist/bsc-smartcontract-caller/win32
          dest: bsc-smartcontract-caller-win32.zip
      - name: zip win64 folder
        uses: papeloto/action-zip@v1
        with:
          files: dist/bsc-smartcontract-caller/win64
          dest: bsc-smartcontract-caller-win64.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            smartcontract-caller-win32.zip
            smartcontract-caller-win64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
