name: Build & Release

on:
  push:
    tags:
      - "v*.*"
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: Install Node.js dependencies in root folder
        run: npm ci
      - name: Install Node.js dependencies in src folder
        run: |
          cd src
          npm install
          cd ..
      - name: Build win32,win64,osx64,linux32,linux64 binaries
        run: npm run build-all --if-present
      - name: "Zip : win32"
        uses: papeloto/action-zip@v1
        with:
          files: dist/smartcontract-caller/win32
          dest: smartcontract-caller-win32.zip
      - name: "Upload artifact : win32"
        uses: actions/upload-artifact@v1
        with:
          name: smartcontract-caller-win32
          path: ${{ github.workspace }}/smartcontract-caller-win32.zip
      - name: "Zip : win64"
        uses: papeloto/action-zip@v1
        with:
          files: dist/smartcontract-caller/win64
          dest: smartcontract-caller-win64.zip
      - name: "Upload artifact : win64"
        uses: actions/upload-artifact@v1
        with:
          name: smartcontract-caller-win64
          path: ${{ github.workspace }}/smartcontract-caller-win64.zip
      - name: "Zip : osx64"
        uses: papeloto/action-zip@v1
        with:
          files: dist/smartcontract-caller/osx64
          dest: smartcontract-caller-osx64.zip
      - name: "Upload artifact : osx64"
        uses: actions/upload-artifact@v1
        with:
          name: smartcontract-caller-osx64
          path: ${{ github.workspace }}/smartcontract-caller-osx64.zip
      - name: "Zip : linux32"
        uses: papeloto/action-zip@v1
        with:
          files: dist/smartcontract-caller/linux32
          dest: smartcontract-caller-linux32.zip
      - name: "Upload artifact : linux32"
        uses: actions/upload-artifact@v1
        with:
          name: smartcontract-caller-linux32
          path: ${{ github.workspace }}/smartcontract-caller-linux32.zip
      - name: "Zip : linux64"
        uses: papeloto/action-zip@v1
        with:
          files: dist/smartcontract-caller/linux64
          dest: smartcontract-caller-linux64.zip
      - name: "Upload artifact : linux64"
        uses: actions/upload-artifact@v1
        with:
          name: smartcontract-caller-linux64
          path: ${{ github.workspace }}/smartcontract-caller-linux64.zip
      - name: "Zip : templates"
        uses: papeloto/action-zip@v1
        with:
          files: configTemplates/
          dest: config-templates.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.workspace }}/smartcontract-caller-win32.zip
            ${{ github.workspace }}/smartcontract-caller-win64.zip
            ${{ github.workspace }}/smartcontract-caller-osx64.zip
            ${{ github.workspace }}/smartcontract-caller-linux32.zip
            ${{ github.workspace }}/smartcontract-caller-linux64.zip
            ${{ github.workspace }}/config-templates.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
